---
title: "Result"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(patchwork)

```

# Fitting Analysis
```{r}
# Load parameter data
param_1 = read_csv("parameter_estimate.csv")
param_2 = read_csv("parameter_estimate2.csv")
param_estimate = rbind(param_1, param_2)


# Output identification table
fit_identify_result = 
  param_estimate %>% 
    mutate(
      n = factor(n),
      ratio = factor(ratio),
      notnull = ifelse(type == "null", 0, 1),
      notnull_est = ifelse(abs(estimate) > 0, 1, 0),
      identify =
        case_when(
          notnull == 1 & notnull_est == 1 ~ "TP",
          notnull == 1 & notnull_est == 0 ~ "FN",
          notnull == 0 & notnull_est == 1 ~ "FP",
          notnull == 0 & notnull_est == 0 ~ "TN"
        )
    ) %>% 
    group_by(sim_time, n, p, ratio, method, type) %>% 
    summarize(
      sensitivity = sum(identify == "TP")/(sum(identify == "TP") + sum(identify == "FN")),
      specificity = sum(identify == "TN")/(sum(identify == "TN") + sum(identify == "FP")),
      precision = sum(identify == "TP")/(sum(identify == "TP") + sum(identify == "FP")),
      accuracy = (sum(identify == "TP") + sum(identify == "TN")) /
        (sum(identify == "TP") + sum(identify == "FP") + sum(identify == "TN") + sum(identify == "FN")),
      F1_score = 2 * precision * sensitivity / (precision + sensitivity)
    )

# set beta for first kind of ratio
p = 100
ratio = c(1, 4, 5)
ps = floor(0.4*p*ratio[1]/sum(ratio))
pwbc = floor(0.4*p*ratio[2]/sum(ratio))
pwai = floor(0.4*p*ratio[3]/sum(ratio))
beta = c(rep(20, ps), rep(0.5, pwbc + pwai), rep(0, p - ps - pwbc - pwai))
# output the beta estimation table
estimate = 
  param_estimate %>% 
  filter(sim_time == num) %>% 
  mutate(type = factor(type, levels = c('strong', 'wbc', 'wai', 'null'))) %>% 
  arrange(type) %>% 
  pull(estimate)
MSE = sum((estimate - beta)^2) / 100
MSE
# Output beta estimation table


# set beta for second kind of ratio
p = 100
ratio = c(3, 3, 4)
ps = floor(0.4*p*ratio[1]/sum(ratio))
pwbc = floor(0.4*p*ratio[2]/sum(ratio))
pwai = floor(0.4*p*ratio[3]/sum(ratio))
beta = c(rep(20, ps), rep(0.5, pwbc + pwai), rep(0, p - ps - pwbc - pwai))
# Output beta estimation table
estimate = 
  param_estimate %>% 
  filter(sim_time == sim_number) %>% 
  mutate(type = factor(type, levels = c('strong', 'wbc', 'wai', 'null'))) %>% 
  arrange(type) %>% 
  pull(estimate)
MSE = sum((estimate - beta)^2) / 100
MSE
```

# Visualization
```{r}
# compare all signals

# compare sensitivity
ggplot(fit_identify_result %>% filter(ratio == 145), aes(x = method, y = sensitivity, color = n)) + 
  geom_boxplot() +
  theme(legend.position = "right") +
  labs(title = "Sensitivity",x = "method", y = "sensitivity")

# compare specificity
ggplot(fit_identify_result, aes(x = method, y = specificity, color = n)) + 
  geom_boxplot() +
  theme(legend.position = "right") +
  labs(title = "specificity",x = "method", y = "specificity")

# compare f1 score
ggplot(fit_identify_result, aes(x = method, y = F1_score, color = n)) + 
  geom_boxplot() +
  theme(legend.position = "right") +
  labs(title = "F1_score",x = "method", y = "F1_score")

# compare accuracy
ggplot(fit_identify_result, aes(x = method, y = accuracy, color = n)) + 
  geom_boxplot() +
  theme(legend.position = "right") +
  labs(title = "accuracy",x = "method", y = "accuracy")
```

```{r}
# compare different signals

# First ratio
# different n sensitivity
ggplot(fit_identify_result %>% filter(n == 100, ratio == 145), aes(x = method, y = sensitivity, color = type)) + 
  geom_boxplot() +
  theme(legend.position = "right") +
  labs(title = "Plot of length  per dose",x = "method", y = "sensitivity")
ggplot(fit_identify_result %>% filter(n == 500, ratio == 145), aes(x = method, y = sensitivity, color = type)) + 
  geom_boxplot() +
  theme(legend.position = "right") +
  labs(title = "Plot of length  per dose",x = "method", y = "sensitivity")
ggplot(fit_identify_result %>% filter(n == 2000, ratio == 145), aes(x = method, y = sensitivity, color = type)) + 
  geom_boxplot() +
  theme(legend.position = "right") +
  labs(title = "Plot of length  per dose",x = "method", y = "sensitivity")

# different n specificity
ggplot(fit_identify_result %>% filter(n == 100, ratio == 145), aes(x = method, y = specificity, color = type)) + 
  geom_boxplot() +
  theme(legend.position = "right") +
  labs(title = "Plot of length  per dose",x = "method", y = "specificity")
ggplot(fit_identify_result %>% filter(n == 500, ratio == 145), aes(x = method, y = specificity, color = type)) + 
  geom_boxplot() +
  theme(legend.position = "right") +
  labs(title = "Plot of length  per dose",x = "method", y = "specificity")
ggplot(fit_identify_result %>% filter(n == 2000, ratio == 145), aes(x = method, y = specificity, color = type)) + 
  geom_boxplot() +
  theme(legend.position = "right") +
  labs(title = "Plot of length  per dose",x = "method", y = "specificity")

# different n F1-score
ggplot(fit_identify_result %>% filter(n == 100, ratio == 145), aes(x = method, y = F1_score, color = type)) + 
  geom_boxplot() +
  theme(legend.position = "right") +
  labs(title = "Plot of length  per dose",x = "method", y = "F1_score")
ggplot(fit_identify_result %>% filter(n == 500, ratio == 145), aes(x = method, y = F1_score, color = type)) + 
  geom_boxplot() +
  theme(legend.position = "right") +
  labs(title = "Plot of length  per dose",x = "method", y = "F1_score")
ggplot(fit_identify_result %>% filter(n == 2000, ratio == 145), aes(x = method, y = F1_score, color = type)) + 
  geom_boxplot() +
  theme(legend.position = "right") +
  labs(title = "Plot of length  per dose",x = "method", y = "F1_score")

# different n accuracy
ggplot(fit_identify_result %>% filter(n == 100, ratio == 145), aes(x = method, y = accuracy, color = type)) + 
  geom_boxplot() +
  theme(legend.position = "right") +
  labs(title = "Plot of length  per dose",x = "method", y = "accuracy")
ggplot(fit_identify_result %>% filter(n == 500, ratio == 145), aes(x = method, y = accuracy, color = type)) + 
  geom_boxplot() +
  theme(legend.position = "right") +
  labs(title = "Plot of length  per dose",x = "method", y = "accuracy")
ggplot(fit_identify_result %>% filter(n == 2000, ratio == 145), aes(x = method, y = accuracy, color = type)) + 
  geom_boxplot() +
  theme(legend.position = "right") +
  labs(title = "Plot of length  per dose",x = "method", y = "accuracy")


# Second ratio
# different n sensitivity
ggplot(fit_identify_result %>% filter(n == 100, ratio == 334), aes(x = method, y = sensitivity, color = type)) + 
  geom_boxplot() +
  theme(legend.position = "right") +
  labs(title = "Plot of length  per dose",x = "method", y = "sensitivity")
ggplot(fit_identify_result %>% filter(n == 500, ratio == 334), aes(x = method, y = sensitivity, color = type)) + 
  geom_boxplot() +
  theme(legend.position = "right") +
  labs(title = "Plot of length  per dose",x = "method", y = "sensitivity")
ggplot(fit_identify_result %>% filter(n == 2000, ratio == 334), aes(x = method, y = sensitivity, color = type)) + 
  geom_boxplot() +
  theme(legend.position = "right") +
  labs(title = "Plot of length  per dose",x = "method", y = "sensitivity")

# different n specificity
ggplot(fit_identify_result %>% filter(n == 100, ratio == 334), aes(x = method, y = specificity, color = type)) + 
  geom_boxplot() +
  theme(legend.position = "right") +
  labs(title = "Plot of length  per dose",x = "method", y = "specificity")
ggplot(fit_identify_result %>% filter(n == 500, ratio == 334), aes(x = method, y = specificity, color = type)) + 
  geom_boxplot() +
  theme(legend.position = "right") +
  labs(title = "Plot of length  per dose",x = "method", y = "specificity")
ggplot(fit_identify_result %>% filter(n == 2000, ratio == 334), aes(x = method, y = specificity, color = type)) + 
  geom_boxplot() +
  theme(legend.position = "right") +
  labs(title = "Plot of length  per dose",x = "method", y = "specificity")

# different n F1-score
ggplot(fit_identify_result %>% filter(n == 100, ratio == 334), aes(x = method, y = F1_score, color = type)) + 
  geom_boxplot() +
  theme(legend.position = "right") +
  labs(title = "Plot of length  per dose",x = "method", y = "F1_score")
ggplot(fit_identify_result %>% filter(n == 500, ratio == 334), aes(x = method, y = F1_score, color = type)) + 
  geom_boxplot() +
  theme(legend.position = "right") +
  labs(title = "Plot of length  per dose",x = "method", y = "F1_score")
ggplot(fit_identify_result %>% filter(n == 2000, ratio == 334), aes(x = method, y = F1_score, color = type)) + 
  geom_boxplot() +
  theme(legend.position = "right") +
  labs(title = "Plot of length  per dose",x = "method", y = "F1_score")

# different n accuracy
ggplot(fit_identify_result %>% filter(n == 100, ratio == 334), aes(x = method, y = accuracy, color = type)) + 
  geom_boxplot() +
  theme(legend.position = "right") +
  labs(title = "Plot of length  per dose",x = "method", y = "accuracy")
ggplot(fit_identify_result %>% filter(n == 500, ratio == 334), aes(x = method, y = accuracy, color = type)) + 
  geom_boxplot() +
  theme(legend.position = "right") +
  labs(title = "Plot of length  per dose",x = "method", y = "accuracy")
ggplot(fit_identify_result %>% filter(n == 2000, ratio == 334), aes(x = method, y = accuracy, color = type)) + 
  geom_boxplot() +
  theme(legend.position = "right") +
  labs(title = "Plot of length  per dose",x = "method", y = "accuracy")

ggplot(fit_identify_result %>% filter(ratio == 334), aes(x = method, y = accuracy, color = type)) + 
  geom_boxplot() +
  theme(legend.position = "right") +
  labs(title = "Plot of length  per dose",x = "method", y = "accuracy") +
  facet_grid(. ~ n)
```
```{r}
# Beta estimation

# MSE of beta for n=100 and ratio 2 
ggplot(fit_beta_result_ratio2 %>% filter(MSE < 1000, n = 100), aes(x = method, y = MSE, color = n)) + 
  geom_boxplot() +
  theme(legend.position = "right") +
  labs(title = "Plot of length  per dose",x = "method", y = "MSE")
```

