---
title: "Simulation"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(MASS)
library(glmnet)
library(tidyverse)
```

# Data Generation
```{r}
# Example 2 of the thesis
# Generate data for simulation study
generate = function(n, # number of observations
                    p, # number of predictors
                    ratio, # ratio of ps, pwbc, pwai and null
                    corr, # correlation coefficient (see example 2)
                    ps = floor(0.4*p*ratio[1]/sum(ratio)), # number of strong signals
                    pwbc = floor(0.4*p*ratio[2]/sum(ratio)), # number of WBC signals
                    pwai = floor(0.4*p*ratio[3]/sum(ratio)), # number of WAI signals
                    c = 20 # the c in the definition of strong and weak 
                    ) {
  
  # Exception stop rules
  if ((ps + pwbc + pwai) >= n) {
    stop("number of true predictors should be less than number of observations")
  }
  if (abs(corr) > 1) {
    stop("correlation coefficient must be between -1 and 1")
  }
  # We hope that beta_strong = 20 and beta_weak = 0.5
  if ((c*sqrt(log(p)/n)) <= 0.5 | (c*sqrt(log(p)/n)) >= 20) {
    stop("please select other n and p")
  }
  
  # Generate correlation matrix based on example 2
  corr_matrix = matrix(rep(0, len = p^2), nrow = p)
  corr_num = pwbc %/% ps
  
  # Correlations between strong & wbc signals (necessary)
  for (i in 1:(ps - 1)) {
    for (j in (ps + 1 + (i - 1)*corr_num):(ps + i*corr_num)) {
      corr_matrix[i, j] = corr
      corr_matrix[j, i] = corr
      # for (k in j:(ps + i*corr_num)) {
      #   corr_matrix[j, k] = corr
      #   corr_matrix[k, j] = corr
      # }
    }
  }
  
  # # Correlations between some wbc signals (unnecessary)
  # for (j in (ps + 1 + (ps - 1)*corr_num):(ps + pwbc)) {
  #   corr_matrix[i, j] = corr
  #   corr_matrix[j, i] = corr
  #   for (k in j:(ps + pwbc)) {
  #     corr_matrix[j, k] = corr
  #     corr_matrix[k, j] = corr
  #   }
  # }
  
  # # Correlations within wai signals (unnecessary)
  # for (j in (ps + pwbc + 1):(ps + pwbc + pwai)) {
  #   for (k in j:(ps + pwbc + pwai)) {
  #     corr_matrix[j, k] = corr
  #     corr_matrix[k, j] = corr
  #   }
  # }
  
  diag(corr_matrix) = 1
  
  # Generate simulation data
  X = mvrnorm(n, mu = rep(0, p), Sigma = corr_matrix, tol = 1)
  beta = c(rep(20, ps), rep(0.5, pwbc + pwai), rep(0, p - ps - pwbc - pwai))
  Y = X %*% beta + rnorm(n, mean = 0, sd = 8)
  df = as.data.frame(cbind(Y, X))
  colnames(df)[1] = "y"
  
  # Rename signals
  for (i in 2:(1 + ps)) {
    colnames(df)[i] = paste("strong", i - 1, sep = "_")
  }
  for (i in (2 + ps):(1 + ps + pwbc)) {
    colnames(df)[i] = paste("wbc", i - 1 - ps, sep = "_")
  }
  for (i in (2 + ps + pwbc):(1 + ps + pwbc + pwai)) {
    colnames(df)[i] = paste("wai", i - 1 - ps - pwbc, sep = "_")
  }
  for (i in (2 + ps + pwbc + pwai):(1 + p)) {
    colnames(df)[i] = paste("null", i - 1 - ps - pwbc - pwai, sep = "_")
  }
  
  return(df)
}
```

# Simulation
```{r, warning=FALSE}
# Simulate 100 times for n and p
simulation = function(n, p, ratio, corr, param_table) {
  param_estimate = param_table
  set.seed(1)
  for (i in 1:100) {
    # Data manipulation
    df = generate(n, p, ratio, corr)
    X = as.matrix(df[1:p + 1])
    Y = as.matrix(df[1])
    
    # Forward Selection
    fit_forward = step(object = lm(y ~ 1, data = df),
                       scope = formula(lm(y ~ ., data = df)),
                       direction = "forward",
                       k = 2,
                       trace = 0)
    param_forward = data.frame(t(fit_forward$coefficients[-1]))
    
    # LASSO
    fit_lasso = cv.glmnet(X, Y, 
                          nfolds = 10, 
                          type.measure = "mse") 
    param_lasso = data.frame(t(fit_lasso$glmnet.fit$beta[, fit_lasso$lambda == fit_lasso$lambda.1se]))
    
    param_estimate_i =
      bind_rows(param_forward, param_lasso) %>% 
      mutate(
        sim_time = i,
        n = n,
        p = p,
        ratio = str_c(ratio,collapse = ''),
        method = c("forward", "lasso")
      ) %>% 
      pivot_longer(
        cols = -c("sim_time", "n", "p", "ratio", "method"),
        names_to = c("type", "num"),
          names_sep = "_",
        values_to = "estimate"
      )
    param_estimate = rbind(param_estimate, param_estimate_i)
  }
  param_estimate[["estimate"]][is.na(param_estimate[["estimate"]])] = 0
  return(param_estimate)
}

# Simulation for first kind of ratio and different n
param_estimate = data.frame(matrix(ncol = 0, nrow = 0))
param_estimate = simulation(n = 100, p = 100, ratio = c(3,6,1), corr = 0.4, param_table = param_estimate)
param_estimate = simulation(n = 500, p = 100, ratio = c(3,6,1), corr = 0.4, param_table = param_estimate)
param_estimate = simulation(n = 2000, p = 100, ratio = c(3,6,1), corr = 0.4, param_table = param_estimate)

# param_estimate = select(param_estimate, sim_time, n, p, method, everything())
write_csv(param_estimate, "parameter_estimate.csv")

# Simulation for second kind of ratio and different n
param_estimate = data.frame(matrix(ncol = 0, nrow = 0))
param_estimate = simulation(n = 100, p = 100, ratio = c(3,3,4), corr = 0.4, param_table = param_estimate)
param_estimate = simulation(n = 500, p = 100, ratio = c(3,3,4), corr = 0.4, param_table = param_estimate)
param_estimate = simulation(n = 2000, p = 100, ratio = c(3,3,4), corr = 0.4, param_table = param_estimate)

# param_estimate = select(param_estimate, sim_time, n, p, method, everything())
write_csv(param_estimate, "parameter_estimate2.csv")
```

# Fitting Analysis

\begin{tabular}{c|c|c|c}
\hline  
Settings & Case 1 & Case 2  \\
\hline  
Number of Predictors & 100 & 500\\
Strong Signals & 3 & 3\\
Weak-Correlated Signals & 30 & 30\\
Weak-Independent Signals & 30 & 30\\
Null Signals & 67 & 67\\
\hline
\end{tabular}


