---
title: "Result"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(patchwork)
library(dplyr)
```

# Fitting Analysis
```{r}
# Load parameter data
param_1 = read_csv("parameter_estimate.csv")
param_2 = read_csv("parameter_estimate2.csv")
param_estimate = rbind(param_1, param_2)


# Output identification table
fit_identify_result = 
  param_estimate %>% 
    mutate(
      n = factor(n),
      ratio = ifelse(ratio == 145, "1:4:5", "3:3:4"),
      notnull = ifelse(type == "null", 0, 1),
      notnull_est = ifelse(abs(estimate) > 0, 1, 0),
      identify =
        case_when(
          notnull == 1 & notnull_est == 1 ~ "TP",
          notnull == 1 & notnull_est == 0 ~ "FN",
          notnull == 0 & notnull_est == 1 ~ "FP",
          notnull == 0 & notnull_est == 0 ~ "TN"
        )
    ) %>% 
    group_by(sim_time, n, p, ratio, method) %>% 
    summarize(
      sensitivity = sum(identify == "TP")/(sum(identify == "TP") + sum(identify == "FN")),
      specificity = sum(identify == "TN")/(sum(identify == "TN") + sum(identify == "FP")),
      precision = sum(identify == "TP")/(sum(identify == "TP") + sum(identify == "FP")),
      accuracy = (sum(identify == "TP") + sum(identify == "TN")) /
        (sum(identify == "TP") + sum(identify == "FP") + sum(identify == "TN") + sum(identify == "FN")),
      F1_score = 2 * precision * sensitivity / (precision + sensitivity)
    )


# Output identification table by signal
fit_identify_result_type = 
  param_estimate %>% 
    mutate(
      n = factor(n),
      ratio = ifelse(ratio == 145, "1:4:5", "3:3:4"),
      notnull = ifelse(type == "null", 0, 1),
      notnull_est = ifelse(abs(estimate) > 0, 1, 0),
      identify =
        case_when(
          notnull == 1 & notnull_est == 1 ~ "TP",
          notnull == 1 & notnull_est == 0 ~ "FN",
          notnull == 0 & notnull_est == 1 ~ "FP",
          notnull == 0 & notnull_est == 0 ~ "TN"
        )
    ) %>% 
    group_by(sim_time, n, p, ratio, method, type) %>% 
    summarize(
      sensitivity = sum(identify == "TP")/(sum(identify == "TP") + sum(identify == "FN")),
      specificity = sum(identify == "TN")/(sum(identify == "TN") + sum(identify == "FP")),
      precision = sum(identify == "TP")/(sum(identify == "TP") + sum(identify == "FP")),
      accuracy = (sum(identify == "TP") + sum(identify == "TN")) /
        (sum(identify == "TP") + sum(identify == "FP") + sum(identify == "TN") + sum(identify == "FN")),
      F1_score = 2 * precision * sensitivity / (precision + sensitivity)
    )



p = 100
ratio = c(1, 4, 5)
ps = floor(0.4*p*ratio[1]/sum(ratio))
pwbc = floor(0.4*p*ratio[2]/sum(ratio))
pwai = floor(0.4*p*ratio[3]/sum(ratio))
beta = c(rep(20, ps), rep(0.5, pwbc + pwai), rep(0, p - ps - pwbc - pwai))
# output the beta estimation table of ratio 1
fit_beta_result_ratio1 = 
  param_1 %>% 
    mutate(
      n = factor(n),
      ratio = ifelse(ratio == 145, "1:4:5", "3:3:4"),
      num = case_when(
  type == "strong" ~ num,
  type == "wbc" ~ num + ps,
  type == "wai" ~ num + ps + pwbc,
  type == "null" ~ num + ps + pwbc + pwai),
      se = (estimate - beta[num])^2
    ) %>% 
    group_by(sim_time, n, p, ratio, method) %>% 
    summarize(
      RMSE = sqrt(mean(se))
    )

# output the beta estimation table of ratio2
p = 100
ratio = c(3, 3, 4)
ps = floor(0.4*p*ratio[1]/sum(ratio))
pwbc = floor(0.4*p*ratio[2]/sum(ratio))
pwai = floor(0.4*p*ratio[3]/sum(ratio))
beta = c(rep(20, ps), rep(0.5, pwbc + pwai), rep(0, p - ps - pwbc - pwai))

fit_beta_result_ratio2 = 
  param_2 %>% 
    mutate(
      n = factor(n),
      ratio = ifelse(ratio == 145, "1:4:5", "3:3:4"),
      num = case_when(
  type == "strong" ~ num,
  type == "wbc" ~ num + ps,
  type == "wai" ~ num + ps + pwbc,
  type == "null" ~ num + ps + pwbc + pwai),
      se = (estimate - beta[num])^2
    ) %>% 
    group_by(sim_time, n, p, ratio, method) %>% 
    summarize(
      RMSE = sqrt(mean(se))
    )

fit_beta_result_ratio = 
  rbind(fit_beta_result_ratio1, fit_beta_result_ratio2)
```

# Visualization
```{r}
# compare all signals

# compare sensitivity
g1 = ggplot(fit_identify_result, aes(x = method, y = sensitivity, color = n)) + 
  geom_boxplot() +
  theme(legend.position = "right") +
  labs(title = "Sensitivity",x = "method", y = "sensitivity") +
  facet_grid(. ~ ratio)
g1
ggsave(g1,filename = "Images/g1.pdf",width = 12,height = 9)

# compare specificity
g2 = ggplot(fit_identify_result, aes(x = method, y = specificity, color = n)) + 
  geom_boxplot() +
  theme(legend.position = "right") +
  labs(title = "Specificity",x = "method", y = "specificity") +
  facet_grid(. ~ ratio)
g2
ggsave(g2,filename = "Images/g2.pdf",width = 12,height = 9)

# compare F1-score
g3 = ggplot(fit_identify_result, aes(x = method, y = F1_score, color = n)) + 
  geom_boxplot() +
  theme(legend.position = "right") +
  labs(title = "F1_score",x = "method", y = "F1_score") +
  facet_grid(. ~ ratio)
g3
ggsave(g3,filename = "Images/g3.pdf",width = 12,height = 9)

# compare accuracy
g4 = ggplot(fit_identify_result, aes(x = method, y = accuracy, color = n)) + 
  geom_boxplot() +
  theme(legend.position = "right") +
  labs(title = "Accuracy",x = "method", y = "accuracy") +
  facet_grid(. ~ ratio)
g4
ggsave(g4,filename = "Images/g4.pdf",width = 12,height = 9)
```

```{r}
# compare different signals

# First ratio
g5 = ggplot(fit_identify_result_type, aes(x = method, y = sensitivity, color = type)) + 
  geom_boxplot() +
  theme(legend.position = "right") +
  labs(title = "Sensitivity",x = "method", y = "sensitivity") +
  facet_grid(ratio ~ n)
g5
ggsave(g5,filename = "Images/g5.pdf",width = 12,height = 9)

g6 = ggplot(fit_identify_result_type, aes(x = method, y = specificity, color = type)) + 
  geom_boxplot() +
  theme(legend.position = "right") +
  labs(title = "Specificity",x = "method", y = "specificity") +
  facet_grid(ratio ~ n)
g6
ggsave(g6,filename = "Images/g6.pdf",width = 12,height = 9)

g7 = ggplot(fit_identify_result_type, aes(x = method, y = F1_score, color = type)) + 
  geom_boxplot() +
  theme(legend.position = "right") +
  labs(title = "F1_score",x = "method", y = "specificity") +
  facet_grid(ratio ~ n)
g7
ggsave(g7,filename = "Images/g7.pdf",width = 12,height = 9)

g8 = ggplot(fit_identify_result_type, aes(x = method, y = accuracy, color = type)) + 
  geom_boxplot() +
  theme(legend.position = "right") +
  labs(title = "Accuracy",x = "method", y = "specificity") +
  facet_grid(ratio ~ n)
g8
ggsave(g8,filename = "Images/g8.pdf",width = 12,height = 9)
```



```{r}
# Beta estimation

# MSE of beta for n = 100
g9 = ggplot(fit_beta_result_ratio %>% filter(n == 100), aes(x = method, y = RMSE)) + 
  geom_boxplot(color = "red", fill = "orange", alpha = 0.5) +
  theme(legend.position = "right") +
  labs(title = "beta RMSE when n = 100",x = "method", y = "RMSE") +
  coord_cartesian(ylim = c(0, 15)) +
  facet_grid(~ ratio)
g9
ggsave(g9, filename = "Images/g9.pdf",width = 12,height = 9)

# MSE of beta for n = 500
g10 = ggplot(fit_beta_result_ratio %>% filter(n == 500), aes(x = method, y = RMSE)) + 
  geom_boxplot(color = "red", fill = "orange", alpha = 0.5) +
  theme(legend.position = "right") +
  labs(title = "beta RMSE when n = 500",x = "method", y = "RMSE") +
  coord_cartesian(ylim = c(0, 0.6)) +
  facet_grid(~ ratio)
g10
ggsave(g10, filename = "Images/g10.pdf",width = 12,height = 9)

# MSE of beta for n = 2000
g11 = ggplot(fit_beta_result_ratio %>% filter(n == 2000), aes(x = method, y = RMSE)) + 
  geom_boxplot(color = "red", fill = "orange", alpha = 0.5) +
  theme(legend.position = "right") +
  labs(title = "beta RMSE when n = 2000",x = "method", y = "RMSE") +
  coord_cartesian(ylim = c(0, 0.4)) +
  facet_grid(~ ratio)
g11
ggsave(g11, filename = "Images/g11.pdf",width = 12,height = 9)
```

